<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $viewModel \Emico\RobinHq\ViewModel\LoggedInCustomer
 */

$viewModel = $block->getViewModel();
if (!$viewModel->shouldRender()) {
    return '';
}
?>
<script type="text/javascript">
    if (typeof __robin !== 'undefined') {
        var robin_settings = {
            callback: function (event, data) {
                if (event == 'init') {
                    var name = '<?= $viewModel->getName(); ?>';		// determine real name
                    var email = '<?= $viewModel->getEmail(); ?>';	// determine real email

                    if (email != null && email != '') {
                        var ws = __robin.getWebStore();


                        ws.conversationTemplate.useAnonymousChat = true;
                        __robin.setShopper(email, name);
                    }
                }
            }
        };
    }

</script>
