language: php
sudo: false
php:
  - '7.3'
  - '7.4'

before_script:
  - composer config -a -g http-basic.repo.magento.com $MAGENTO_USERNAME $MAGENTO_PASSWORD
  - composer install --no-plugins

script:
  - vendor/bin/codecept run unit