language: php
sudo: false
image: php:7.2

before_script:
  - composer config -a -g http-basic.repo.magento.com $MAGENTO_USERNAME $MAGENTO_PASSWORD
  - composer install --no-plugins

test:
  script:
    - vendor/bin/codecept run