<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $viewModel \Emico\RobinHq\ViewModel\LoggedInCustomer
 */

$viewModel = $block->getViewModel();
if (!$viewModel->shouldRender()) {
    return '';
}
?>
<script type="text/javascript">
    if (typeof __robin !== 'undefined') {
        var customer = getCustomer();
        var robin_settings = {
            callback: function (event, data) {
                if (event == 'init') {
                    var name = customer.fullname;	// determine real name
                    var email = customer.email;	    // determine real email

                    if (email != null && email != '') {
                        var ws = __robin.getWebStore();


                        ws.conversationTemplate.useAnonymousChat = true;
                        __robin.setShopper(email, name);
                    }
                }
            }
        };
    }

    /**
     * Get the customer from the local storage, because the PHP customer session is depersonalized on cached pages
     * @returns {Object}
     */
    function getCustomer()
    {
        if (localStorage.getItem('mage-cache-storage') != null) {
            var mageCacheStorage = JSON.parse(localStorage.getItem('mage-cache-storage'));

            if (typeof mageCacheStorage.customer !== 'undefined') {
                return mageCacheStorage.customer;
            }

        }
        return {
            fullName: 'Unknown',
            email: 'unknown@unknown.com'
        };
    }
</script>
